language: android

android:
  components:
    - build-tools-21.1.2
    - extra-android-m2repository
    - extra-google-m2repository
    - android-21

jdk:
  - oraclejdk6
  - openjdk6

before_install:
  # environment info
  - gradle -v
  - uname -a

  # ensure gradlew is executeable
  - chmod +x gradlew

sudo: false

cache:
  directories:
    - $HOME/.gradle/caches/

script:
  - ./gradlew clean :library:assemble :library:test :library:jacocoTestReport :library:coveralls

after_script:
  - coveralls
