language: android
android:
  components:
  - build-tools-21.1.2
  - extra-android-m2repository
  - extra-google-m2repository
  - android-21
jdk:
- oraclejdk8
before_install:
- export TERM=dumb
- chmod +x gradlew
- "./gradlew -v"
- uname -a
sudo: false
cache:
  directories:
  - "$HOME/.gradle/caches/"
script:
- "./gradlew clean :sixpack-java:assemble :sixpack-java:test"
after_success:
- "./gradlew :sixpack-java:jacocoTestReport :sixpack-java:coveralls"
- buildscripts/deploy_snapshot.sh
env:
  global:
  - secure: pSvokts6jEcSrePh0OAOPrnpdob7gyD9MqgfPY2IeD+60zrstmrlH28VjAlROV2IWrZoBNYknQwnbmeX1b79hBiqFTBbIFPqx71iA+F0Rda8hC4pLkbGwtE88HluqORa36b5Q6U+J8ose3f9nyxpMLjnUabTH2QaCdU64UC5YPC7712IR3NpXZdirX1SsuySFBcVeNMdEqQpKdYbwnZ0GGNQ7oE0oRqznFBtaSIW2wh4BtVAOqam7gYRs4Bqcm0x4UElSwicDrtEMIbjIlom06zQLSR0MeOLCUP9ULRHuFYBHCbBduXSWg1RJm/8uQvLpQBjrIae8oVKdxrizcz+/00oNOybJOWtCPcoZWh5tQzhl/VhtcXlvsQbKZyTCEU+kKtHPW5GTC7z8yiT1DtmKaySvp22oBpMJsII2M4eNdanmaPTKHACc4e9LcGI/MFNA5MN+Kb5plL4J5+dC2X11AMLKoeFqanZ7Q3TjQXfAhCRLQ+1tCgQ8Rh2tmUAPESGDFHEGkGyWO9Xrjil/BIlDb/uIjHNP930SaZcD6i8lgVoF4pOP5dfS2bz0CU/S2NcoEL4u2eHDvzIYKm1sFtA60SdjA7A/rdVDB5XaQUwDW7v6yCsSrY24DG/u+Q5FcglunzkpNyxqjsDrqIqLysGYeUsk07ggaYvjfBBG6EEt68=
  - secure: uQqaeLGguld/syXsV0lbyw/0oKj2XXtJlUP3l4LbiFSFn11ELQj0/PIW7TllhlwVx29boFlYCIRZ+fRw/Lb2HrW93t+GP7cNXW6kq2NXNYAn+/3q4u//vr8uiWu943S2Lklup3CE6GsyXlsIgk0fRjxwiHpumdKpvjz8VtNqWwKZy1+IVqxEQfbPYFlqzrUZj/XsYENpFgbpMu6QG/iTQdv+0Tc9WaylPq7D3WLoqvBJ47slRvoVgSxGyCqGby2/17k6NtN2tUKyhzg/YFojgtOLCgGX0y7baYvOILMPptqru5JrPVJun2FuV/wqY6h5tAxwKxOdAd+82WENbA82+2D6mllZ6/Gm1HMW73iimGO4WpCKD++KJlM/M3vN8Rsa/cIMOB70JLPl9k80ckb1GjrMjafMzVk/cgNWXI6b+D3qDcUAgXyXmft/v6Ao7khqvt2TtvM5KiqO6EC9efYUV5UP3CHK/vgpQRIbwNomdJgFQBXw8LtwerYkZ7fxEFIvvTPQbb16Y6WoYNBTfG2xXpYeYE1Kfe5deSO2bPDHE3k73CighZ3Wuiglkt2DTe3qb9eC/dg/OAp3hO6dl/i4eGBHJXjLUDl/svNqjNU7CUvtGtr82GzB6kbq52yAbVZBgQeBYpCOl+d+D8ig1j57PmZfBE/o+YVsAbW/dCcKp5U=
