language: android
android:
  components:
  - build-tools-21.1.2
  - extra-android-m2repository
  - extra-google-m2repository
  - android-21
jdk:
- oraclejdk8
before_install:
- export TERM=dumb
- chmod +x gradlew
- ./gradlew -v
- uname -a
sudo: false
cache:
  directories:
  - $HOME/.gradle/caches/
script:
- ./gradlew clean :sixpack-java:assemble :sixpack-java:test
after_success:
- ./gradlew :sixpack-java:jacocoTestReport :sixpack-java:coveralls
- buildscripts/deploy_snapshot.sh
env:
  global:
  - secure: "VHMQpLDlOJI14OZP8Z2lRwK7YEa6uDxkHDTNRIxL/FRLH2XwAHXxRA1qfHTSMN6nUXUq9CS1Qckbv/m3A2azjvYVYpbl/YtfgbbuGPixqhNS53DFl1ZOC0EXOlWA3SgNgLrJ7RbclfUrjeJ73YyBMCTItz98g3HI9IU638/F5zckLeMg2hhjDMXa1aXbp1qn0RDiJi8suQzsjxq0Wplb8s9uR/sgxilA3bDIifH8OMMA0ZauJ7lSVLs6WNRI9biSXbKclPCNL/Oqnl5YVxTxzLkcXzIC79LMf+9CCoHb44SYfOQud4bpvGf5/M/CTwsAgqZW2VgDUxeqMTtIqEpM1N8Z/EnGBz0yzb3jdhtLK7l2Rt5BYRAFmlgNIq1Zy575/jK8FxGd3B8m/RDF8se4qYk9UK+otVQT8JfOXIdvRdbjuVerA5EHVjWxkgG1BgjnfHgY9HRSMVQzI1B80lrRKeNVDFdSvprzFt1LYaN5XmP74wlgn0D3mEMHLK6rNuJlCdjXm+98lVyxublJhxQXnbvGdoCYeojxMrkm/TT6aiwj1KjPdPYuVPZAxnmVQaWpKz3bzX4mt8c/S52fxMCTN16EdU6pk6/SIEKws8yN2C7YnFeA53G8X0lC6bi33sV1qUG/fQvOTw8jZFUrdmQPUlGvGNjxDacbqOVwFCtH53I="
  - secure: "ILlA8eBy/V2cnSUg+vn4RUSA5NKPJXDKZoJ0Th0hJpAboay6u6Ke0Hlq+PnGpZ/j61OtJccFyNRqVkaNGDWob2ztyzzrXTgC+MWPUvDfag9BT9Ysm0oh10CnnZQzs1hzHJtx0d0SSD678jf5+P6PRHXzMlsN3UA3x0uoacQTAGRe0jCZIj6TWnUMgAoT6WBBpv+WdEua2MlWgeKy7dsN5te3GpI+tFd9H3wDiA+0kUTmPgFwoso5uS+oThesm/sCpq3tcPYJvtFri31+QPXsQ9UwZWCHDkvtA2XnVDHiW7Dj3sG1z1TzIvV6oNhyDkaMAmReCOLY/Sq+8/Nmy8BzlLxpbneJMi7zzkXgruvX9lC6xXkG3dNvn6S0+8ZbB0KGsDUhsKlkkDDQWKNCSVEPL7kMKms3oN3nE0Hp+LnD2ylkxXlXnuuwUklKh82d/CUO9I4tLT94dx/MChUNzMDVm9taYtd/H1MBlIlpiDd/aELwckMmMGzqh7I6qzKxzoKpHChiKGsLnsFhIqIMPhbBzVLKfCc304dml6YxjwnhEt1PvyZd5t/vhWs7uQNhMqPt8hvZMEazC3wthjspLWt89ueZfiYVuwESC33f9DMnM5EeFS2x1rQBbq+qrkhqoUxN+CT+ve53Bc9IorzeLA4JTICszGxRRblpYuKwBOkoM6I="
