language: android

android:
  components:
    - build-tools-21.1.2
    - extra-android-m2repository
    - extra-google-m2repository
    - android-21

jdk:
  - oraclejdk8

before_install:
  # for gradle output style
  - export TERM=dumb

  # ensure gradlew is executeable
  - chmod +x gradlew
  
  # environment info
  - ./gradlew -v
  - uname -a

sudo: false

cache:
  directories:
    - $HOME/.gradle/caches/

script:
  - ./gradlew clean :library:assemble :library:test :library:jacocoTestReport :library:coveralls

after_script:
  - coveralls
