language: android
android:
  components:
  - build-tools-21.1.2
  - extra-android-m2repository
  - extra-google-m2repository
  - android-21
jdk:
- oraclejdk8
before_install:
- export TERM=dumb
- chmod +x gradlew
- ./gradlew -v
- uname -a
sudo: false
cache:
  directories:
  - $HOME/.gradle/caches/
script:
- ./gradlew clean :sixpack-java:assemble :sixpack-java:test
after_success:
- ./gradlew :sixpack-java:jacocoTestReport :sixpack-java:coveralls
- buildscripts/deploy_snapshot.sh
env:
  global:
  - secure: P1ehMlSzqv9hjJyIH3VxQ8HxjgCd4ROnIeRynjr0HifLt4viEuIaPSoOFM7e/QwKHVU1/IoX1NjYD7BLlLBSb2yhdKburXkTM8RK3iG1BcL36k0h6GkOTSSVU9I8IYKaOn/zdz50bcvK1W/aJgBhqoNwQ4ku9fViGCWyBQTUYVg=
  - secure: GjZfwGIEpmavGgV1kd3n2oFySeQnXWHovcy397TX8OdL2vrwv9fh+EhDsqO70E7Dg6r5EYORMtjXoThd47w65uqu8+ukYuVTu/kc6MGe2H/5aHcOcUJ3zybawCLEPaYskO8Daz/JwnQkytO5eyONnYhztFu0Yx1uKdpXfjnIuu0=
