language: android
android:
  components:
  - build-tools-21.1.2
  - extra-android-m2repository
  - extra-google-m2repository
  - android-21
jdk:
- oraclejdk8
before_install:
- export TERM=dumb
- chmod +x gradlew
- "./gradlew -v"
- uname -a
sudo: false
cache:
  directories:
  - "$HOME/.gradle/caches/"
script:
- "./gradlew clean :sixpack-java:assemble :sixpack-java:test"
after_success:
- "./gradlew :sixpack-java:jacocoTestReport :sixpack-java:coveralls"
- buildscripts/deploy_snapshot.sh
env:
  global:
  - secure: NuL2kYPwlZxwRtqvL7LcUnzGAr7YaIX8bfkVODggw+pSw2Fb7i1tpjfYxy6B0rVhN7jjsSDrwii6dWm8cDoOlCI5w6DXRKgsKv6WznH1RKp173QkSoWoqCOngEmffy9KWNC3kavknVMFXmK3j2f434d5ntfM8OPpcocEEtr9KebNsemCrNRCXPJwu7GlZVJi69YUuM1uAz5jOXkaNxM8ge7hMCwMpZ+DoOVcGGH69EM9Hpw9bd3e7ML6jM2JjT8EvdgbD9MDeGbxwCxo+o7/PlYo+guroWefCTnVavfyaHls5VFQ9ySuuWUAbsa9NyKoMmL+0i1cc988guOmOKXcavrnUxRl2R0qQIP9mJfk0Ewxqs1S+cCn/MZbsUSmJzumET+niezFoHyyOcKR8wEF7Mir9D+LWWzOOqSSsxqcfbpa/KoDUPsxjmqn7uwB9P2ebs+RM77+mHU5L+FU7W0bObAqS1KDXcfYOOOj+5Txc/S46vMQJgBF/dcgcHVNpQQk93fpIzN8dNYMuqaHL+NJm709OPfVAz538MDz2obCm02O1Lcu/rXV0IYuIh+DIk42Tju2eFiK/QIK1dVC0P/SGGkU2X/mHEureBmR5CXAg3K19cmfxDw0GWJ3OPzmCRKRO8vrK/8+6H0sYGTYMLBRMQBQpp6XkVOrV561gN9srkI=
  - secure: yRTG5VBZHimm9Jc53qm7aS3463JnN8Wqo6VDdei15CHRpqVnfEYBjil1tvoYsNx699RMH93U2MEsPQyUa76Y41GqsjwEfA3M+hPWJlfJzchTs20jwFsGPkq1quNiHXKk7DJC9DQL+zZ2kRUcL/ZXxU/S6gC6IgoZmV+Vy92S48HPWepf59dY78h05bVMpOOBSDdvWDgH9SlmOtI+G5FK1qhXDRdBjYOjkwWsdPNaj8+BxnYUzIgLUkPNE3SVNYdtug2EPVjJP5omxLClOzCu8e0Dd0K1kC1IJxSScnVRLmMgjT6Sx5/gSNod/wFv/BJUNoYGeQxK1n6ZmajoStXLMNj181I61qrndWYPcVe45WzZYpy689frBDHDKN6kATfDPlGVSq6itAG5SAKnOgqqaldGWsGKbEoY0m9LlfFUEL8McVsDvvhNPICnfbwqmNmKVqN3YepOEBtOEAV5Xc3Vb+RfzPHQVpbdVyBo52R4w5J1InxSCdevONkX9UOzxbjFTgqP3Xprim7S5ZpoyVR9vHX+A33PJW59wLEZJzJ2IOt2VefQx5cYN3t0/rRH+Zj59qngMI6p7h5Ku1oUojnh3KYcF10jM3KiJfL+IBSZ2Qsgi8KZJselb6cUQL741etEv9HuG+/JpqVJZTRTRN8fJ3WkB0v9H+hMfpiSj9IAh4s=
